# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)


platform :ios do
 
  desc 'iOS: Increment build number and set the version to package.json version.'
  private_lane :inc_ver_ios do  
    package = load_json(json_path: "../package.json")
    version = package['version']
    increment_build_number_in_plist
    increment_version_number(
      xcodeproj: package['name'] + '.xcodeproj',
      version_number: package['version']
    )
  end
  
  desc "Build without code sign. Just to see if the build is working"
  lane :build do |options|
    build_app(
      workspace: "MyExpenses.xcworkspace",
      configuration: "Debug",
      scheme: "MyExpenses",
      silent: true,
      clean: true,
      output_directory: "path/to/dir", # Destination directory. Defaults to current directory.
      output_name: "my-expenses.ipa",       # specify the name of the .ipa file to generate (including file extension)
    )
  end
end
